version: "3.8"

services:
  express-api:
    build: .
    ports:
      - "3001:3001"
    env_file:  # <-- NEU/KORRIGIERT: Umgebungsvariablen aus .env laden
      - .env
    # volumes: # <-- ENTFERNT/AUSKOMMENTIERT: Diese Zeile für .env verursachte Probleme
    #   - ./.env:/app/.env
    restart: always